export const icon = {
    back:require('./icon/backIcon.png'),
    cart:require('./icon/shopCart.png'),
    share:require('./icon/shareIcon.png'),
    email:require('./icon/indexEmail.png'),
    indexCart:require('./icon/indexShopCart.png'),
    paySuccess:require('./icon/pay/paySuccess.png'),
    payFail:require('./icon/pay/payFail.png'),
    payZfb:require('./icon/pay/payZfb.png'),
    payWx:require('./icon/pay/payWx.png'),
    storeIcon:require('./icon/storeIcon.png'),
    customerIcon:require('./icon/customerIcon.png'),
    collectIcon0:require('./icon/collectIcon0.png'),
    collectIcon1:require('./icon/collectIcon1.png'),
    closeIcon:require('./icon/closeIcon.png'),
    addressIcon:require('./icon/addressIcon.png'),
    address: require('./icon/addr/addRess.png'),
    orderTopLine: require('./icon/addr/orderTopLine.png'),
    addRessBg: require('./icon/addr/addRessBg.png'),
    exCar: require('./icon/exCar.png'),
    dfkIco: require('./icon/userCenter/dfkIco.png'),
    dfhIco: require('./icon/userCenter/dfhIco.png'),
    dshIco: require('./icon/userCenter/dshIco.png'),
    dpjIco: require('./icon/userCenter/dpjIco.png'),
    ywcIco: require('./icon/userCenter/ywcIco.png'),
    thIco: require('./icon/userCenter/thIco.png'),
    uDefaultImg: require('./icon/userCenter/uDefaultImg.png'),
    // uBg: require('./icon/userCenter/uBg.png'),
};

export const test = {
    test1:require('./test/1.jpg'),
    test2:require('./test/2.jpg'),
    test3:require('./test/3.jpg'),
    test4:require('./test/4.png'),
    test5:require('./test/5.png'),
    test6:require('./test/6.png'),
    test7:require('./test/7.png'),
    test8:require('./test/8.jpg'),
    test9:require('./test/9.jpg'),
    banner1:require('./test/banner1.jpg'),
    banner2:require('./test/banner2.jpg'),
    u1: require('./test/u1.png'),
    
}